### ISSUE TITLE
Create a contributor guide

### ISSUE THREAD

**Issue by ibutiti** [Friendsofthepeople/django-recall-server#1]
I'd like to contribute to this but don't know how.

Some questions:
- Issue templates
- Who are the core contributors (code reviewers, issue triage etc)
- Git workflow

**Comment by Friendsofthepeople** [comment]
Hello,
We are setting that up with time as we improve the documentation. For now,
kindly keep the suggestions coming as well as making your own pull requests.

Many thanks,

**Comment by C-o-m-o-n** [comment]
> I'd like to contribute to this but don't know how.
> 
> Some questions:
> 
> * Issue templates
> * Who are the core contributors (code reviewers, issue triage etc)
> * Git workflow

we have set up a minimal but informative contributors guide, so your now welcome to start your contributions. Kep in minde we are still updating the whole project. This includes the guide. Kindly make sure you check it out more often and update your side accordingly. 
Thanks.
Happy hacking with you! :)

**Comment by John-Njau** [comment]
> > I'd like to contribute to this but don't know how.
> > Some questions:
> > 
> > * Issue templates
> > * Who are the core contributors (code reviewers, issue triage etc)
> > * Git workflow
> 
> we have set up a minimal but informative contributors guide, so your now welcome to start your contributions. Kep in minde we are still updating the whole project. This includes the guide. Kindly make sure you check it out more often and update your side accordingly. Thanks. Happy hacking with you! :)

I would suggest we work on a contribution guide first. This will streamline everything going forward. 

Additionally, let's follow good coding practices from the onset:
> feature branches
> pull requests
> proper commit messages etc
