### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by joseph-njogu** [Friendsofthepeople/django-recall-server#15]
Document APIs to ease the process of consuming them by the frontend team. This will include adding Swagger ui.

**Comment by C-o-m-o-n** [comment]
> Document APIs to ease the process of consuming them by the frontend team. This will include adding Swagger ui.

The documentation has already been implemented by @carlagesa and it was merged yesterday.  Try pulling the latest changes

**Comment by joseph-njogu** [comment]
Cool, thanks for this
