### ISSUE TITLE
Maintainability

### ISSUE THREAD

**Issue by robinmuhia** [Friendsofthepeople/django-recall-server#17]
Very good initiative.

However, this project  will have a lot of contributors hence we need to architect our code structure, maintainability and readability early before we accumulate technical debt.

I will follow this up with a large Pull Request to try and make our code maintainable

**Comment by C-o-m-o-n** [comment]
> Very good initiative.
> 
> However, this project  will have a lot of contributors hence we need to architect our code structure, maintainability and readability early before we accumulate technical debt.
> 
> I will follow this up with a large Pull Request to try and make our code maintainable  

That would be very nice of you. Whenever you are ready with the Pull Request, feel free to open it. 

Happy hacking with you :)

**Comment by apexDev37** [comment]
Good initiative! Given this is in the initial stages, I'd advocate for considerable effort to go into the project's test suite🧪
Well-covered and _testable_ software is the cornerstone of reliable and maintainable software.
The following is a fraction of the benefits of investing in a comprehensive test suite:

- Prevents over-time [regression](https://en.wikipedia.org/wiki/Software_regression#:~:text=A%20software%20regression%20is%20a,new%20features%20and%20bug%20fixes.) of the codebase
- Provides users a safety net to fall back to production-ready states
- Gives quantifiable metrics and empirical evidence that the software behaves as expected.
- Increases developer productivity by reducing mean time to detection (MTTD) and mean time to recovery (MTTR)

**Comment by robinmuhia** [comment]
> Good initiative! Given this is in the initial stages, I'd advocate for considerable effort to go into the project's test suite🧪 Well-covered and _testable_ software is the cornerstone of reliable and maintainable software. The following is a fraction of the benefits of investing in a comprehensive test suite:
> 
> * Prevents over-time [regression](https://en.wikipedia.org/wiki/Software_regression#:~:text=A%20software%20regression%20is%20a,new%20features%20and%20bug%20fixes.) of the codebase
> * Provides users a safety net to fall back to production-ready states
> * Gives quantifiable metrics and empirical evidence that the software behaves as expected.
> * Increases developer productivity by reducing mean time to detection (MTTD) and mean time to recovery (MTTR)

I agree hence the introduction of pytest and a tests folder as well as the ci.yaml

**Comment by apexDev37** [comment]
While skimming through the repo, I noticed minor yet fundamental patches that should be added.

@robinmuhia Kindly add a [task list](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists) on the issues you are working on.
This will save time and avoid duplicate work from other contributors working on issues you're tackling

**Comment by apexDev37** [comment]
> I agree hence the introduction of pytest and a tests folder as well as the ci.yaml

Would the team prefer to write [`pytest`](https://docs.pytest.org/en/stable/contents.html) or [`unittest`](https://docs.python.org/3/library/unittest.html) based tests?
I've seen teams write `unittest` based tests and use `pytest` for execution (test runner).
Apart from the learning curve, I recommend full adoption of the `pytest` framework, both as the test style and execution

**Comment by robinmuhia** [comment]
> While skimming through the repo, I noticed minor yet fundamental patches that should be added.
> 
> @robinmuhia Kindly add a [task list](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists) on the issues you are working on. This will save time and avoid duplicate work from other contributors working on issues you're tackling

Currently, I am not working on anything at the moment...maybe next weekend i can setup the tests and checks for linting etc

**Comment by apexDev37** [comment]
> Currently, I am not working on anything at the moment...maybe next weekend i can setup the tests and checks for linting etc

Noted. @robinmuhia Kindly note the tasks I aim to resolve this week in the following issue: #31
