### ISSUE TITLE
Deployability

### ISSUE THREAD

**Issue by C-o-m-o-n** [Friendsofthepeople/django-recall-server#30]
Deployment of the  server is using docker is not working.  Changes to the configuration files needed.
@robinmuhia , kindly look through the code and suggest any changes

**Comment by robinmuhia** [comment]
What provider are you deploying to?
What errors are you getting?

**Comment by robinmuhia** [comment]
I can see that with the docker-compose.yml, migrations are never ran. Might that be the issue?

**Comment by C-o-m-o-n** [comment]
> What provider are you deploying to?
> What errors are you getting?

We'll be deploying to aws. But I was trying to deploy to render, to test things out

**Comment by C-o-m-o-n** [comment]
> I can see that with the docker-compose.yml, migrations are never ran. Might that be the issue?

Yes I personally removed it because it was giving me issues with gituhb actions. Let me  put it back and see if it'll work

**Comment by robinmuhia** [comment]
> > What provider are you deploying to?
> > What errors are you getting?
> 
> We'll be deploying to aws. But I was trying to deploy to render, to test things out

Okay, in case of any errors, just let me know
