### ISSUE TITLE
Core repository and setup files

### ISSUE THREAD

**Issue by apexDev37** [Friendsofthepeople/django-recall-server#31]
## Overview
Certain key files are absent from the repository to support a consistent local environment across different platforms.

## Intended Outcome
- Include files at the **repository level** to mirror file handling and checkout behavior across various host machines.
- Include files at the **editor/IDE level** to sync settings and configurations for consistency across files.
- Include files at the **application level** to support local development best practices.

### Chores
- [x] Clean up and prevent checkout of python bytecode (cache) files
- [x] Add example/sample env file for users
- [x] Add `.gitattributes` to control file and checkout behavior
- [x] Add `.editorconfig` to sync editor/IDE settings across local environments
- [x] Migrate to use faster linter `ruff`
- [x] Enforce uniform and opinionated code style `black`
- [x] Add `pre-commit` config to run local continuous integration checks at the _commit-level_

## References
> Links for details on the proposed tools

- [Black](https://github.com/psf/black): Opinionated Python code formatter
- [EditorConfig](https://editorconfig.org/): Config file to define editor/IDE rules
- [Pre-Commit](https://pre-commit.com/): Multi-language pre-commit hooks manager.
- [Ruff](https://github.com/astral-sh/ruff): An extremely fast Python linter and formatter

**Comment by apexDev37** [comment]
I can take up one task each day and resolve each issue by the end of the week⚡

**Comment by robinmuhia** [comment]
> I can take up one task each day and resolve each issue by the end of the week⚡

black is already there and in a previous MR, i had added lint checks but the author removed that check...

**Comment by ndiku** [comment]
Can I take up some of these?

**Comment by C-o-m-o-n** [comment]
> Can I take up some of these?

Sure

**Comment by ndiku** [comment]
> > Can I take up some of these?
> 
> Sure

Ok. Who assigns issues?

**Comment by C-o-m-o-n** [comment]
> ## Overview
> Certain key files are absent from the repository to support a consistent local environment across different platforms.
> 
> ## Intended Outcome
> * Include files at the **repository level** to mirror file handling and checkout behavior across various host machines.
> * Include files at the **editor/IDE level** to sync settings and configurations for consistency across files.
> * Include files at the **application level** to support local development best practices.
> 
> ### Chores
> * [ ]  Clean up and prevent checkout of python bytecode (cache) files
> * [ ]  Add example/sample env file for users
> * [ ]  Add `.gitattributes` to control file and checkout behavior
> * [ ]  Add `.editorconfig` to sync editor/IDE settings across local environments
> * [ ]  Migrate to use faster linter `ruff`
> * [ ]  Enforce uniform and opinionated code style `black`
> * [ ]  Add `pre-commit` config to run local continuous integration checks at the _commit-level_
> 
> ## References
> > Links for details on the proposed tools
> 
> * [Black](https://github.com/psf/black): Opinionated Python code formatter
> * [EditorConfig](https://editorconfig.org/): Config file to define editor/IDE rules
> * [Pre-Commit](https://pre-commit.com/): Multi-language pre-commit hooks manager.
> * [Ruff](https://github.com/astral-sh/ruff): An extremely fast Python linter and formatter



> > > Can I take up some of these?
> > 
> > 
> > Sure
> 
> Ok. Who assigns issues?

I do

**Comment by ndiku** [comment]
Ok. Please assign me the first 3 for now.

**Comment by ndiku** [comment]
> > ## Overview
> > Certain key files are absent from the repository to support a consistent local environment across different platforms.
> > ## Intended Outcome
> > 
> > * Include files at the **repository level** to mirror file handling and checkout behavior across various host machines.
> > * Include files at the **editor/IDE level** to sync settings and configurations for consistency across files.
> > * Include files at the **application level** to support local development best practices.
> > 
> > ### Chores
> > 
> > * [ ]   Clean up and prevent checkout of python bytecode (cache) files
> > * [ ]   Add example/sample env file for users
> > * [ ]   Add `.gitattributes` to control file and checkout behavior
> > * [ ]   Add `.editorconfig` to sync editor/IDE settings across local environments
> > * [ ]   Migrate to use faster linter `ruff`
> > * [ ]   Enforce uniform and opinionated code style `black`
> > * [ ]   Add `pre-commit` config to run local continuous integration checks at the _commit-level_
> > 
> > ## References
> > > Links for details on the proposed tools
> > 
> > 
> > 
> > * [Black](https://github.com/psf/black): Opinionated Python code formatter
> > * [EditorConfig](https://editorconfig.org/): Config file to define editor/IDE rules
> > * [Pre-Commit](https://pre-commit.com/): Multi-language pre-commit hooks manager.
> > * [Ruff](https://github.com/astral-sh/ruff): An extremely fast Python linter and formatter
> 
> > > > Can I take up some of these?
> > > 
> > > 
> > > Sure
> > 
> > 
> > Ok. Who assigns issues?
> 
> I do

Ok. Please assign me the first 3 for now.

**Comment by ndiku** [comment]
> > > ## Overview
> > > Certain key files are absent from the repository to support a consistent local environment across different platforms.
> > > ## Intended Outcome
> > > 
> > > * Include files at the **repository level** to mirror file handling and checkout behavior across various host machines.
> > > * Include files at the **editor/IDE level** to sync settings and configurations for consistency across files.
> > > * Include files at the **application level** to support local development best practices.
> > > 
> > > ### Chores
> > > 
> > > * [ ]    Clean up and prevent checkout of python bytecode (cache) files
> > > * [ ]    Add example/sample env file for users
> > > * [ ]    Add `.gitattributes` to control file and checkout behavior
> > > * [ ]    Add `.editorconfig` to sync editor/IDE settings across local environments
> > > * [ ]    Migrate to use faster linter `ruff`
> > > * [ ]    Enforce uniform and opinionated code style `black`
> > > * [ ]    Add `pre-commit` config to run local continuous integration checks at the _commit-level_
> > > 
> > > ## References
> > > > Links for details on the proposed tools
> > > 
> > > 
> > > 
> > > * [Black](https://github.com/psf/black): Opinionated Python code formatter
> > > * [EditorConfig](https://editorconfig.org/): Config file to define editor/IDE rules
> > > * [Pre-Commit](https://pre-commit.com/): Multi-language pre-commit hooks manager.
> > > * [Ruff](https://github.com/astral-sh/ruff): An extremely fast Python linter and formatter
> > 
> > 
> > > > > Can I take up some of these?
> > > > 
> > > > 
> > > > Sure
> > > 
> > > 
> > > Ok. Who assigns issues?
> > 
> > 
> > I do
> 
> Ok. Please assign me the first 3 for now.
> > > * [ ]    Clean up and prevent checkout of python bytecode (cache) files
> > > * [ ]    Add example/sample env file for users
> > > * [ ]    Add `.gitattributes` to control file and checkout behavior

**Comment by ndiku** [comment]
Thanks. Later!

**Comment by C-o-m-o-n** [comment]
> Thanks. Later!

Thanks for your interests to make this project better.
Happy hacking with you :)

**Comment by apexDev37** [comment]
> Can I take up some of these?

Hey @ndiku, sure! Though I already checked out a local branch with most of these changes.
In the interest of avoiding duplicate work... What's your progress on the tasks?

**Comment by ndiku** [comment]
Hey @apexDev37, Kindly go ahead and do the PR for those; I wouldn't want your effort to go to waste. I'll pick others to work on.

**Comment by apexDev37** [comment]
Thanks @ndiku,
Creating the PR once I'm done resolving lint errors:
```
(drs-py310) ➜  drs git:(patch-repo-setup) ✗ ruff check . --no-fix
...
...  # checks
...
Found 200 errors.
[*] 26 fixable with the `--fix` option (13 hidden fixes can be enabled with the `--unsafe-fixes` option).
(drs-py310) ➜  drs git:(patch-repo-setup) ✗ 
```

It would be counterintuitive to adopting the new linter, `ruff`, if the repo was pushed in a state violating lint and quality checks.

**Comment by C-o-m-o-n** [comment]
> Thanks @ndiku, Creating the PR once I'm done resolving lint errors:
> 
> ```
> (drs-py310) ➜  drs git:(patch-repo-setup) ✗ ruff check . --no-fix
> ...
> ...  # checks
> ...
> Found 200 errors.
> [*] 26 fixable with the `--fix` option (13 hidden fixes can be enabled with the `--unsafe-fixes` option).
> (drs-py310) ➜  drs git:(patch-repo-setup) ✗ 
> ```
> 
> It would be counterintuitive to adopting the new linter, `ruff`, if the repo was pushed in a state violating lint and quality checks.

Hey, @apexDev37 How re you doing, any updte?

**Comment by apexDev37** [comment]
> Hey, @apexDev37 How re you doing, any update?

Hey @C-o-m-o-n, doing good!

**Comment by C-o-m-o-n** [comment]
> > Hey, @apexDev37 How re you doing, any update?
> 
> Hey @C-o-m-o-n, doing good!
> I'm almost done with the pre-commit config to automate the quality checks. I'll open a PR tomorrow⚡
> 

Cool
